routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/cv','CvController');
Route::resource('/settings','SettingController');
Route::get('/dashboard','DashboardController@index')->name('dashboard.index');


Route::get('/payment/with-paypal/{cvid}','PaymentsController@paywithPaypal');
Route::get('/payment/success/{cvid}/','RegisterController@store');

Route::get('/payment/fails/err',function(){
	return "fails";
});

Route::get('/payment/process', 'PaymentsController@process')->name('payment.process');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class DashboardController extends Controller
{
	public function __construct()
    {
        $this->middleware('auth',['execpt' => ['logout']]);
    }

    public function index()
    {
        return view('dashboard/index');
    }
}

resources/views/dashboard/index.blade.php
@extends('layouts.app')
@section('content')
	<section>
		<div class="container">
			<div class="row">
				<div class="col-md-12" >
					<div class="col-md-6 col-md-offset-4">
						<h1>Admin Dashboard</h1>
						<div>
						  <a href="{{ route('cv.index') }}">Cv List</a>
						  <a href="{{ route('settings.show',1) }}">Settings</a>
						  <a href="#">Banner</a>
						  <a href="#">Promotional Banners</a>
						</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
@endsection