routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/cv','CvController');
Route::resource('/settings','SettingController');
Route::get('/dashboard','DashboardController@index')->name('dashboard.index');


Route::get('/payment/with-paypal/{cvid}','PaymentsController@paywithPaypal');
Route::get('/payment/success/{cvid}/','RegisterController@store');

Route::get('/payment/fails/err',function(){
	return "fails";
});

Route::get('/payment/process', 'PaymentsController@process')->name('payment.process');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Models/Cv.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Cv extends Model
{
    //

    public function user() {
        return $this->hasOne('cvsite\Models\User');
    }
}

app/Http/Controllers/CvController.php
<?php

namespace App\Http\Controllers;

use App\Models\Cv;
use App\Models\Setting;
use App\Services\Interfaces\ICvService;
use Illuminate\Http\Request;

class CvController extends Controller
{

    public $CvService;

    public function __construct(ICvService $cvService)
    {
        $this->CvService = $cvService;
        $this->middleware('auth',['except' => ['logout','create','store']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cvs = $this->CvService->getAllCvs();
        return view('cv/index')->withCvs($cvs);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('cv/create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $cv = $this->CvService->create($request);


        $cvId=$cv->id;

        $settings=Setting::find(1);
        $amount=$settings->amount;

        return view('payment')->withCvId($cvId)->withAmount($amount);

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Cv $cv)
    {
        $cv = $this->CvService->getCv($cv);
        return view("cv/show")->withCv($cv);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Cv $cv)
    {
        return view('cv.edit')->withCv($cv);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Cv $cv)
    {
        $this->CvService->update($request, $cv);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Cv $cv)
    {
        $this->cvService->delete($cv);
    }
}

resources/views/cv/create.blade.php
@extends('layouts.app')
@section('content')
    <article class="main-heading">
        <div class="container">
            <div class="row-content100">
                <div class="col-xs-12">
                    <h1 class="text-center">Create CV</h1>
                </div>
            </div>
        </div>
    </article>
    <section class="cv-section">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <div class="row row-content">
                        <div class="col-md-9 col-md-offset-3">
                            <div class="panel-body">
                                <!-- Display Validation Errors -->
                                {{-- @include('common.errors') --}}
                                <form action="{{ route('cv.store') }}" method="POST" accept-charset="UTF-8" enctype="multipart/form-data">
                                    {{ csrf_field() }}
                                    {{ method_field('POST') }}
                                    @include('cv.cvForm')
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <link href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.css" rel="stylesheet" type="text/css"/>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
       @if(Session::has('message'))
        var type = "{{ Session::get('alert-type', 'info') }}";
        switch (type) {
            case 'info':
                toastr.info("{{ Session::get('message') }}");
                break;

            case 'warning':
                toastr.warning("{{ Session::get('message') }}");
                break;
            case 'success':
                toastr.success("{{ Session::get('message') }}");
                break;
            case 'error':
                toastr.error("{{ Session::get('message') }}");
                break;
        }
        @endif
      </script>
@endsection

resources/views/cv/cvForm.blade.php
<div class="row ">
    <div class="col-xs-12 col-sm-7 ">
        <div class="form-group ">
            <label for="firstName">First Name <span class="error">*</span></label>
            <input type="text" name="firstName" id="firstName" class="form-control"
                   @if(isset($cv->firstName)) value="{{$cv->firstName}}" @else placeholder="First Name" @endif required >
        </div>
    </div>
</div>
<div class="row ">
    <div class="col-xs-12 col-sm-7 ">
        <div class="form-group ">
            <label for="lastName">Last Name <span class="error">*</span></label>
            <input type="text" name="lastName" id="lastName" class="form-control"
                   @if(isset($cv->lastName)) value="{{$cv->lastName}}" @else placeholder="Last Name" @endif required >
        </div>
    </div>
</div>
<div class="row">
    <div class="col-xs-12 col-sm-7 ">
        <div class="form-group">
            <label for="gender">Gender</label><br>
            <input name="gender" type="radio" value="male" 
            @if(isset($cv->gender) && $cv->gender == 'male') 
                checked="checked" 
            @endif ><label for="male"> Male</label><br>
            <input name="gender" type="radio" value="female" 
            @if(isset($cv->gender) && $cv->gender == 'female')) 
                checked="checked"
            @endif><label for="female"> Female</label>
        </div>
    </div>
</div>
<div class="row ">
    <div class="col-xs-12 col-sm-7 ">
        <div class="form-group ">
            <label for="email">Email <span class="error">*</span></label>
            <input type="email" name="email" id="email" class="form-control"
                   @if(isset($cv->email)) value="{{$cv->email}}" @else placeholder="Email" @endif required >
        </div>
    </div>
</div>
<div class="row ">
    <div class="col-xs-12 col-sm-7 ">
        <div class="form-group ">
            <label for="phone">Phone <span class="error">*</span></label>
            <input type="number" name="phone" id="phone" class="form-control"
                   @if(isset($cv->phone)) value="{{$cv->phone}}" @else placeholder="Phone" @endif required >
        </div>
    </div>
</div>
<div class="row ">
    <div class="col-xs-12 col-sm-7 ">
        <div class="form-group ">
            <label for="jobInterestedArea">Job Interested Area</label>
            <input type="text" name="jobInterestedArea" id="jobInterestedArea" class="form-control"
                   @if(isset($cv->jobInterestedArea)) value="{{$cv->jobInterestedArea}}" @else placeholder="Job Interested Area" @endif required >
        </div>
    </div>
</div>
<div class="row ">
    <div class="col-xs-12 col-sm-7 ">
        <div class="form-group ">
            <label for="file">Upload A CV</label>
            <input type="file" name="file" id="file">
            @if(isset($cv->file)) 
                {{$cv->file}}
            @endif
        </div>
    </div>
</div>

<div class="row">
    <div class="row-content100">
        <div class="col-xs-12 col-sm-4 col-sm-offset-4">
            <div class="form-group">
                <button type="submit" class="button40 button">
                    <i class=""></i> {{isset($cv)? "Update": "Add"}} CV
                </button>
            </div>
        </div>
    </div>
</div>

resources/views/cv/edit.blade.php
@extends('layouts.app')
@section('content')
    <section class="cv-section">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <div class="row row-content">
                        <div class="col-md-9 col-md-offset-3">
                            <div class='panel-body'>
                                <!-- Display Validation Errors -->
                                {{-- @include('common.errors') --}}
                                <form action="{{ route('cv.update',$cv->id) }}" method="POST"
                                      class="form-horizontal">
                                    {{ csrf_field() }}
                                    {{ method_field('PUT') }}
                                    @include('cv.cvForm')
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/cv/index.blade.php
@extends('layouts.app')
@section('content')
   @if (count($cvs) > 0)
    <article class="cv-list-section">
       
        <div class="container">
            <div class="row">
                <div class="col-md-12 content-center">
                    <h3>List of Cvs</h3>
                    <div class="table-responsive">
                        <table class="table table-condensed  table-bordered table-striped table-hover">
                            <thead>
                            <th>Name</th>
                            <th>Gender</th>
                            <th>Email</th>
                            <th>Phone</th>
                            <th>Job Interested Area</th>
                            <th>Actions</th>
                            <th>Posted On</th>
                            </thead>
                            <tbody>
                            @foreach ($cvs as $cv)
                                <tr>
                                    <td>{{ $cv->name }}</td>
                                    <td>{{ $cv->gender }}</td>
                                    <td>{{ $cv->email }}</td>
                                    <td>{{ $cv->phone }}</td>
                                    <td>{{ $cv->jobInterestedArea }}</td>
                                    <td>{{  date('M j, Y h:ia', strtotime($cv->date)) }}</td>
                                    <td>
                                        <a href="{{ route('cv.show',$cv->id) }}" class="btn btn-default button20 btn-sm">Show</a> 
                                        <a href=""  class="btn btn-primary button20 btn-sm">Download</a>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                      @else
                          <h3>Currently, there are no Cv's</h3>
                    </div>
                </div>
            </div>
        </div>
    </article>
@endif
@endsection

resources/views/cv/show.blade.php
@extends('layouts.app')
@section('content')
    <article class="main-heading">
        <div class="container">
            <div class="row-content100">
                <div class="col-xs-12">
                    <h1 class="text-center">CV Details</h1>
                </div>
            </div>
        </div>
    </article>
    <section class="cv-view">
        <div class="container">
            <div class="row row-content">
                <div class="col-xs-12">
                    <div class="panel-body">
                        <div class='col-md-6 col-md-offset-3'>
                            <ul class="list-group">
                                <li class="list-group-item"><strong>ID:</strong>  {{$cv->id}}</li>
                                <li class="list-group-item"><strong>Name:</strong>   {{$cv->name}}</li>
                                <li class="list-group-item"><strong>Gender:</strong> {{ $cv->gender }}</li>
                                <li class="list-group-item"><strong>Email:</strong>    {{$cv->email}}</li>
                                <li class="list-group-item"><strong>Phone:</strong>    {{ $cv->phone  }}</li>
                                <li class="list-group-item"><strong>Job Interested Area:</strong>   {{ $cv->jobInterestedArea  }}</li>
                                <li class="list-group-item"><strong>Posted On:</strong>{{  date('M j, Y h:ia', strtotime($cv->date)) }}</li>
                            </ul>
                            <a href="" class="btn btn-primary">Download</a><p>{{ $cv->file }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection