routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/cv','CvController');
Route::resource('/settings','SettingController');
Route::get('/dashboard','DashboardController@index')->name('dashboard.index');


Route::get('/payment/with-paypal/{cvid}','PaymentsController@paywithPaypal');
Route::get('/payment/success/{cvid}/','RegisterController@store');

Route::get('/payment/fails/err',function(){
	return "fails";
});

Route::get('/payment/process', 'PaymentsController@process')->name('payment.process');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Models/Setting.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Setting extends Model
{
	
}

app/Http/Controllers/SettingController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Setting;
use App\Services\Interfaces\ISettingService;

class SettingController extends Controller
{

    public $SettingService;

    public function __construct(ISettingService $settingService)
    {
        $this->SettingService = $settingService;
        $this->middleware('auth',['execpt' => ['logout']]);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Setting $setting)
    {
        return view('setting/show')->withSetting($setting);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Setting $setting)
    {
        return view('setting/edit')->withSetting($setting);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Setting $setting)
    {
        $this->SettingService->updateSetting($request,$setting);
        return redirect()->route('settings.show',$setting->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/setting/edit.blade.php
@extends('layouts.app')
@section('content')
    <section class="cv-section">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <div class="row row-content">
                        <div class="col-md-9 col-md-offset-3">
                            <div class='panel-body'>
                                <!-- Display Validation Errors -->
                                {{-- @include('common.errors') --}}
                                <form action="{{ route('settings.update',$setting->id) }}" method="POST"
                                      class="form-horizontal">
                                    {{ csrf_field() }}
                                    {{ method_field('PUT') }}
                                    @include('setting.settingForm')
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/setting/settingForm.blade.php
<div class="row ">
    <div class="col-xs-12 col-sm-7 ">
        <div class="form-group ">
            <label for="paypalClientId">Paypal Client Id</label>
            <input type="text" name="paypalClientId" id="paypalClientId" class="form-control"
                   @if(isset($setting->paypal_client_id)) value="{{$setting->paypal_client_id}}" @else placeholder="Paypal Client Id" @endif required >
        </div>
    </div>
</div>
<div class="row ">
    <div class="col-xs-12 col-sm-7 ">
        <div class="form-group ">
            <label for="paypalClientSecret">Paypal Client Secret</label>
            <input type="text" name="paypalClientSecret" id="paypalClientSecret" class="form-control"
                   @if(isset($setting->paypal_client_secret)) value="{{$setting->paypal_client_secret}}" @else placeholder="Paypal Client Secret" @endif required >
        </div>
    </div>
</div>
<div class="row ">
    <div class="col-xs-12 col-sm-7 ">
        <div class="form-group ">
            <label for="amount">Amount</label>
            <input type="text" name="amount" id="amount" class="form-control"
                   @if(isset($setting->amount)) value="{{$setting->amount}}" @else placeholder="Amount" @endif required >
        </div>
    </div>
</div>
<div class="row">
    <div class="row-content100">
        <div class="col-xs-12 col-sm-4 col-sm-offset-4">
            <div class="form-group">
                <button type="submit" class="button40 button">
                    <i class=""></i> {{isset($setting)? "Update": "Add"}} CV
                </button>
            </div>
        </div>
    </div>
</div>

resources/views/setting/show.blade.php
@extends('layouts.app')
@section('content')
    <article class="main-heading">
        <div class="container">
            <div class="row-content100">
                <div class="col-xs-12">
                    <h1 class="text-center">Settings</h1>
                </div>
            </div>
        </div>
    </article>
    <section class="cv-view">
        <div class="container">
            <div class="row row-content">
                <div class="col-xs-12">
                    <div class="panel-body">
                        <div class='col-md-6 col-md-offset-3'>
                            <ul class="list-group">
                                <li class="list-group-item"><strong>Paypal Client Id:</strong>{{$setting->paypal_client_id}}</li>
                                <li class="list-group-item"><strong>Paypal Client Secret:</strong> {{ $setting->paypal_client_secret }}</li>
                                <li class="list-group-item"><strong>Amount:</strong>    {{$setting->amount}}</li>
                            </ul>
                            <a href="{{ route('settings.edit',$setting->id) }}" class="btn btn-default">Edit</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection