routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/cv','CvController');
Route::resource('/settings','SettingController');
Route::get('/dashboard','DashboardController@index')->name('dashboard.index');


Route::get('/payment/with-paypal/{cvid}','PaymentsController@paywithPaypal');
Route::get('/payment/success/{cvid}/','RegisterController@store');

Route::get('/payment/fails/err',function(){
	return "fails";
});

Route::get('/payment/process', 'PaymentsController@process')->name('payment.process');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('css/style.css') }}" type="text/css">
     <link rel="stylesheet" href="{{ asset('css/font-awesome.min.css') }}" type="text/css">
     <link rel='stylesheet prefetch' href='https://fonts.googleapis.com/icon?family=Material+Icons'>
    <link href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.css" rel="stylesheet" type="text/css"/>
    <link rel='stylesheet prefetch' href='https://cdnjs.cloudflare.com/ajax/libs/owl-carousel/1.3.3/owl.carousel.css'>
     <link rel='stylesheet prefetch' href='https://cdnjs.cloudflare.com/ajax/libs/owl-carousel/1.3.3/owl.theme.css'>
  
</head>
<body>
@include('layouts.header')
<div id="app">
<nav class="navbar navbar-inverse " role="navigation">
           <div class="container">
                <div class="navbar-header">
                     
                   
                   <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                       <span class="sr-only">Toggle navigation</span>
                       <span class="icon-bar"></span>
                       <span class="icon-bar"></span>
                       <span class="icon-bar"></span>
                   </button>
                    {{-- <a class="navbar-brand" href="#"><img src="assets/img/logo.png" height=30 width=41 alt="Confusion logo" title="Confusion Resturant"></a> --}}
                   
               </div>
               <div  id="navbar" class="navbar-collapse collapse">
               <ul class="nav navbar-nav">
                <li class="active"><a href="/">HOME</a></li>
                <li><a href="About.html">WHO WE ARE</a></li>
                <li ><a href="contactus.html">WHAT WE DO</a></li>
                 <li  ><a href="contactus.html">SERVICES</a></li>
                 <li  ><a href="{{ route('cv.create')}}">ADD CV</a></li>
                 <li  ><a href="contactus.html">CONTACTS</a></li>
                <li><a href="https://twitter.com"  target="_blank"><i class="fa fa-twitter"></i></a></li>
                 <li><a href="https://facebook.com"  target="_blank"> <i class="fa fa-facebook"></i></a></li>
                 <li><a href="https://linkedin.com"  target="_blank"> <i class="fa fa-linkedin"></i></i></a></li>
                </ul>
                <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->

                        @guest
                            <li><a href="{{ route('login') }}"> Login</a></li>
                            <li><a href="{{ route('register') }}"> Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endguest
                    </ul>
                 </div>
           </div>
       </nav>
       </div>
      {{--   <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse" aria-expanded="false">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @guest
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav> --}}
       
        @yield('content')
    
   <footer>
    @include('layouts.footer')
   </footer>
    <!-- Scripts -->
    <script type="text/javascript" src="{{ asset('js/jquery-3.2.1.min.js') }}"></script>
    <script src="{{ asset('js/app.js') }}"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/owl-carousel/1.3.3/owl.carousel.min.js"></script>
    <script type="text/javascript" src="{{ asset('js/bootstrap.min.js') }}" async></script>
    {{--  <script type="text/javascript" src="{{ asset('js/owl.carousel.js') }}"></script> --}}
     <script type="text/javascript" src="{{ asset('js/custom-carousel.js') }}"></script>
   {{--  <script type="text/javascript" src="{{ URL::asset('js/custom.js')}}"></script> --}}
   
</body>
</html>

resources/views/layouts/footer.blade.php
<footer class="row-footer">
       <div class="container">
           <div class="row">            
               <div class="col-xs-12  col-lg-3">
                   <h5>Navigation</h5>
                   <hr>
                   <ul class="list-unstyled">
                       <li><a href="#">Home</a></li>
                       <li><a href="#">WHO WE ARE</a></li>
                       <li><a href="#">WHAT WE DO</a></li>
                       <li><a href="#">SERVICES</a></li>
                       <li><a href="#">NEWS</a></li>
                       <li><a href="#">CONTACTS</a></li>
                   </ul>
               </div>
               <div class="col-xs-12  col-lg-3">
               <h5>Our Perception</h5>
               <hr>
               <p>
                 orem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque pharetra pulvinar eros ut porttitor. Donec hendrerit volutpat viverra. Nunc metus ipsum, dignissim vel accumsan vel, convallis id risus
               </p>
               </div>
               <div class="col-xs-12 col-lg-3">
                <h5>Facebook lite box</h5>
                <hr>
                  <div class="panel panel-default">
                    <div class="panel-heading fc">
                      <p class="panel-title">Find us on Facebook </p>
                      <span class="col-md-offset-1 col-sm-offset-1 col-xs-offset-1">facebook</span>
                    </div>
                    <div class="panel-body">
                      <div class="media">
                        <div class="media-left media-middle">
                          <a href="#">
                           <img src="{{ asset('images/welcome/media.jpg') }}" class="media-object"
                                  alt="img">
                            
                          </a>
                        </div>
                         <h4 >Media heading</h4>
                          
                    </div>
                    </div>
                  </div>
               </div>
               <div class="col-xs-12 col-lg-3">
                   <h5>Quick Contact</h5>
                    <hr>
                   <address>
                      121, Clear Water Bay Road<br>
                      Clear Water Bay, Kowloon<br>
                      Dubai<br>
                      <i class="fa fa-phone"></i>: +852 1234 5678<br>
                      <i class="fa fa-fax"></i>: +852 8765 4321<br>
                      <i class="fa fa-envelope"></i>:
                       <a href="mailto:dubai@cv.net">dubai@cv.net</a>
                   </address>
                    <ul class="list-inline">
                       <li>
                       <li>
                       <a class="btn btn-social-icon btn-facebook" href="http://www.facebook.com/profile.php?id="><i class="fa fa-facebook  "></i></a>  
                       </li>
                         <a class="btn btn-social-icon btn-google-plus" href="http://google.com/+"><i class="fa fa-google-plus"></i></a>
                       </li>
                       <li>
                         <a class="btn btn-social-icon btn-twitter" href="http://twitter.com/"><i class="fa fa-twitter"></i></a>
                      </li>
                       <li>
                          <a class="btn btn-social-icon btn-linkedin" href="http://www.linkedin.com/in/"><i class="fa fa-linkedin"></i></a>
                       </li>
                    </div>
              
               
               <div class="col-xs-12">
                   <p style="padding:10px;"></p>
                   <p align=center>© Copyright 2018</p>
               </div>
           </div>
       </div>
   </footer>

resources/views/layouts/header.blade.php
<header class="head-top-area">
<div class="container">
    <div class="row">
        <div class="col-lg-3 col-lg-offset-0 col-sm-6 col-sm-offset-3">
            <img src="{{ asset('images/logo.png') }}"
               class="img-responsive"  alt="MEC-Logo" width="295px" height="90px">
        </div>
        <div class="col-lg-3 col-lg-offset-2 col-xs-offset-0 col-xs-12">
            <div class="header-flex">
                    <i class="fa fa-phone fa-4x"></i>
                    <div>
                    <p> +92-300123456 
                    <br> WhatsApp Online Support</p> 
                    </div>
            </div>
        </div>
        <div class="col-lg-4 fct">
        <div class="pull-right">
        <i class="fa fa-user-circle fa-2x"></i>
        <span>Mustafa LoggedIn</span></br>
        <input type="button" name="" class="button button40" style="margin-top: 0;" value="Register Now">
        </div>
        </div>
    </div>
</div>
     
</header>
 